### ISSUE TITLE
No working.

### ISSUE THREAD

**Issue by iKamus** [DragDay7/Aseprite-buildtool#1]
Nothing happen when  use this thing, it dont show any error or where it is locate, also the description u give is very small, what we should change or for put path...

**Comment by DragDay7** [comment]
Hey mate,

I'll try to make it more user friendly by describing every step script file does and what to edit. There's also change in Skia lib so I have to recompile it again.

Also sorry for late reply - I just realized Github won't make me watch repo I make, even with this setting enabled so I had no idea you wrote.

**Comment by DragDay7** [comment]
@iKamus your issue should be resolved. If you need help I'll reply much quicker now.
